/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PergMate.java
 *
 * Created on 16/09/2011, 12:33:01
 */
package schoolmaster10;
import schoolmaster10.PerguntasMaster;
import javax.swing.*;
public class PergMate extends javax.swing.JFrame {

    /** Creates new form PergMate */
    public PergMate() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        perg1 = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        perg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matemática");

        perg1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perg1.setForeground(new java.awt.Color(255, 255, 255));
        perg1.setText("1-  2 mim e 54 s equivale a quantos segundo?");

        op1.setBackground(new java.awt.Color(0, 153, 153));
        op1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("184");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op2.setBackground(new java.awt.Color(0, 153, 153));
        op2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("174");
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        op3.setBackground(new java.awt.Color(0, 153, 153));
        op3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("164");
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op4.setBackground(new java.awt.Color(0, 153, 153));
        op4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("166");
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        perg2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perg2.setForeground(new java.awt.Color(255, 255, 255));
        perg2.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addComponent(op4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(perg2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(perg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(perg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perg2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op4)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            int x=1;int cont=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (x == 1) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("2-Marcos tinha 12 caixas com 30 cadernos cada uma. Ele");
            perg2.setText(" achou mais 3 cadernos.Quantos cadernos ele tem agora ?");
            op1.setText("363");
            op2.setText("383");
            op3.setText("366");
            op4.setText("373");
        }
        if (x == 2) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("3-Quocinte e Resto respectivos da divisão 47/7 ?");
            perg2.setText("");
            op1.setText("7 e 6");
            op2.setText("5 e 7");
            op3.setText("6 e 8");
            op4.setText("6 e 5");
        }
        if (x == 3) {
            if (op4.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: D");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: D");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("4- Qual é o resultado da equação x+(2.4)+7x=0 ?");
            op1.setText("3");
            op2.setText("12");
            op3.setText("1");
            op4.setText("7");
        }
        if (x == 4) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("5-Um oitavo de uma pizza custa 3 reais, quanto custa: 3/8 ");
            perg2.setText("dessa mesma?");
            op1.setText("12");
            op2.setText("9");
            op3.setText("18");
            op4.setText("15");
        }
        if (x == 5) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("6-Dada a fração 869/1000 que numero decimal ele ");
            perg2.setText("representa? ");
            op1.setText("0,888");
            op2.setText("0,869");
            op3.setText("0,0893");
            op4.setText("0,869");
        }
        if (x == 6) {
            if (op4.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: D");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: D");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("7- Qual a média aritmetica de 1,2,3,4,5,6,7,8,9?");
            perg2.setText("");
            op1.setText("5");
            op2.setText("13");
            op3.setText("8");
            op4.setText("17");
        }
        if (x == 7) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("8- A quantia de R$ 1143,00 representa qual porcentagem ");
            perg2.setText("de R$ 2540,00?");
            op1.setText("55%");
            op2.setText("50%");
            op3.setText("45%");
            op4.setText("35%");
        }
        if (x == 8) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("9-Quais são os 5 primeiros múltiplos comuns de 8 e de 12?");
            perg2.setText("");
            op1.setText(" 0, 24, 48, 72, 96");
            op2.setText(" 8, 12, 24, 48, 72");
            op3.setText("12, 24, 48, 72, 96");
            op4.setText(" 8, 24, 48, 72, 96");
        }
        if (x == 9) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("10- A idade de Pedro é 30 anos e a idade de João é 45 anos.");
            perg2.setText("Qual é a razão entre as idades de Pedro e João?");
            op1.setText("3/4");
            op2.setText("1/2");
            op3.setText("2/3");
            op4.setText("3/5");
            
        }
        if (x == 10) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            JOptionPane.showMessageDialog(null,"Você Acertou:"+cont+"/10 questões");
            new PerguntasMaster().show();
            this.dispose();
        }
        x++;
}//GEN-LAST:event_jButton1ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(true);
}//GEN-LAST:event_op4ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(true);
        op4.setSelected(false);
}//GEN-LAST:event_op3ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        op1.setSelected(false);
        op2.setSelected(true);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op2ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        op1.setSelected(true);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PergMate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JLabel perg1;
    private javax.swing.JLabel perg2;
    // End of variables declaration//GEN-END:variables
}
