/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PergFisi.java
 *
 * Created on 12/10/2011, 22:47:11
 */
package schoolmaster10;
import javax.swing.*;
/**
 *
 * @author Douglas
 */
public class PergFisi extends javax.swing.JFrame {

    /** Creates new form PergFisi */
    public PergFisi() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perg1 = new javax.swing.JLabel();
        perg2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        perg1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perg1.setForeground(new java.awt.Color(255, 255, 255));
        perg1.setText("1-Qual a unidade de medida da Aceleração?");
        perg1.setName("perg1"); // NOI18N

        perg2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        perg2.setForeground(new java.awt.Color(255, 255, 255));
        perg2.setName("perg2"); // NOI18N

        jButton1.setText("Confirmar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        op1.setBackground(new java.awt.Color(0, 153, 153));
        op1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("m/s");
        op1.setName("op1"); // NOI18N
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op2.setBackground(new java.awt.Color(0, 153, 153));
        op2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("m/s²");
        op2.setName("op2"); // NOI18N
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        op3.setBackground(new java.awt.Color(0, 153, 153));
        op3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("s/m");
        op3.setName("op3"); // NOI18N
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op4.setBackground(new java.awt.Color(0, 153, 153));
        op4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("km/h");
        op4.setName("op4"); // NOI18N
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Física");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op1)
                                    .addComponent(op2)
                                    .addComponent(op3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perg2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perg1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(perg1)
                .addGap(5, 5, 5)
                .addComponent(perg2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op4)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int x=1,cont=0;
    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        op1.setSelected(false);
        op2.setSelected(true);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op2ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        op1.setSelected(true);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op1ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(true);
        op4.setSelected(false);
}//GEN-LAST:event_op3ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(true);
}//GEN-LAST:event_op4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (x == 1) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("2-A Termologia é o estudo de que?");
            perg2.setText(" ");
            op1.setText("o estudo da temperatura dos corpos");
            op2.setText("o estudo do grau de agitação das moleculas");
            op3.setText("o estudo da energia térmica em trânsito");
            op4.setText("o estudo da quantidade de moleculas");
        }
        if (x == 2) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("3- Quem Formulou a Teoria da Relatividade?");
            perg2.setText(" ");
            op1.setText("Isaac Newton");
            op2.setText("Galileu Galilei");
            op3.setText("Niels Bohr");
            op4.setText("Albert Einstein");
        }
        if (x == 3) {
            if (op4.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: D");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: D");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("4-Um corpo saiu do reposso e chegou até 200m");
            perg2.setText("em 10s qual é a sua velocidade média?");
            op1.setText("20 m/s");
            op2.setText("40 m/s");
            op3.setText("25 m/s");
            op4.setText("35 m/s");
        }
        if (x == 4) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("5-Qual é a velocidade da Luz aproximadamente");
            perg2.setText("");
            op1.setText("150.000.000 m/s");
            op2.setText("300.000.000 m/s");
            op3.setText("250.000.000 m/s");
            op4.setText("400.000.000 m/s");
        }
        if (x == 5) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("6-Qual é a unidade de medida da corrente eletrica?");
            perg2.setText(" ");
            op1.setText("ampère (A)");
            op2.setText("volt(V)");
            op3.setText("watt (W)");
            op4.setText("ohm (Ω)");
        }
        if (x == 6) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("7-o que é Potência eletrica ");
            perg2.setText("");
            op1.setText("Quantidade de energia convertida em um dado intervalo");
            op2.setText("Grandeza proveniente dos níveis subatómicos.");
            op3.setText("Efeito produzido por uma carga o qual pode exercer força");
            op4.setText("Quantidade de carga ");
        }
        if (x == 7) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("8-Qual desses NÃO é um fenônemo físico?");
            perg2.setText(" ");
            op1.setText("A queda de um corpo");
            op2.setText("O enferrujamento do ferro");
            op3.setText("A reflexão da luz em um espelho");
            op4.setText("Dilatação dos corpos");
        }
        if (x == 8) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("9-O que é velocidade média?");
            perg2.setText(" ");
            op1.setText("a distância percorida");
            op2.setText("a variação da posição no espaço em relação ao tempo");
            op3.setText("o movimento do corpos"); 
            op4.setText("a movimentação");
        }
        if (x == 9) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("10-A transmissão de calor por convecção só é  possível");
            perg2.setText(" ");
            op1.setText("no vácuo");
            op2.setText("nos sólidos");
            op3.setText("nos fluidos em geral");
            op4.setText("nos gases");
            
        }
        if (x == 10) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            JOptionPane.showMessageDialog(null,"Você Acertou:"+cont+"/10 questões");
            new PerguntasMaster().show();
            this.dispose();
        }
        x++;
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PergFisi().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JLabel perg1;
    private javax.swing.JLabel perg2;
    // End of variables declaration//GEN-END:variables
}
