/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PergQuim.java
 *
 * Created on 13/10/2011, 22:53:21
 */
package schoolmaster10;
import javax.swing.*;
/**
 *
 * @author Douglas
 */
public class PergQuim extends javax.swing.JFrame {

    /** Creates new form PergQuim */
    public PergQuim() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perg1 = new javax.swing.JLabel();
        perg2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        perg1.setFont(new java.awt.Font("Tahoma", 1, 12));
        perg1.setForeground(new java.awt.Color(255, 255, 255));
        perg1.setText("1-O que é o átomo?");
        perg1.setName("perg1"); // NOI18N

        perg2.setFont(new java.awt.Font("Tahoma", 1, 12));
        perg2.setForeground(new java.awt.Color(255, 255, 255));
        perg2.setName("perg2"); // NOI18N

        jButton1.setText("Confirmar");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        op1.setBackground(new java.awt.Color(0, 153, 153));
        op1.setFont(new java.awt.Font("Tahoma", 0, 12));
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("Uma particula de materia de qualquer tamanho");
        op1.setName("op1"); // NOI18N
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });

        op2.setBackground(new java.awt.Color(0, 153, 153));
        op2.setFont(new java.awt.Font("Tahoma", 0, 12));
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setText("A maior particula de materia");
        op2.setName("op2"); // NOI18N
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });

        op3.setBackground(new java.awt.Color(0, 153, 153));
        op3.setFont(new java.awt.Font("Tahoma", 0, 12));
        op3.setForeground(new java.awt.Color(255, 255, 255));
        op3.setText("A menor particula de materia");
        op3.setName("op3"); // NOI18N
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });

        op4.setBackground(new java.awt.Color(0, 153, 153));
        op4.setFont(new java.awt.Font("Tahoma", 0, 12));
        op4.setForeground(new java.awt.Color(255, 255, 255));
        op4.setText("Metade da materia");
        op4.setName("op4"); // NOI18N
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quimica");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op4)
                            .addComponent(op1)
                            .addComponent(op2)
                            .addComponent(op3)))
                    .addComponent(perg2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perg1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(perg1)
                .addGap(5, 5, 5)
                .addComponent(perg2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(op1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op4)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        int x=1,cont=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (x == 1) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("2-Quem formulou o primeiro modelo atômico");
            perg2.setText(" ");
            op1.setText("Rutherford");
            op2.setText("Niels Bohr ");
            op3.setText("Dalton");
            op4.setText("Thomson");
        }
        if (x == 2) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("3-'Au' Significa qual elemento na tabela periodica" );
            perg2.setText(" ");
            op1.setText("Ouro");
            op2.setText("Prata");
            op3.setText("Aluminho");
            op4.setText("Cobre");
        }
        if (x == 3) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("4-Qual dessas partes do atomo é positiva?");
            perg2.setText(" ");
            op1.setText("eletrons");
            op2.setText("protons");
            op3.setText("neutrons");
            op4.setText("fóton");
        }
        if (x == 4) {
            if (op2.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: B");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: B");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("5-Qual desse fenômenos é endotermicos");
            perg2.setText("");
            op1.setText("Queima da glicose");
            op2.setText("combustões");
            op3.setText("Queima do gás de cozinha");
            op4.setText("Gelo derretendo");
        }
        if (x == 5) {
            if (op4.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: D");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: D");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("6-Qual o numero atomico do Magnesio ");
            perg2.setText(" ");
            op1.setText("22");
            op2.setText("15");
            op3.setText("12");
            op4.setText("25");
        }
        if (x == 6) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("7- O que é Entalpia ");
            perg2.setText("");
            op1.setText("A máxima energia de um sistema termodinâmico");
            op2.setText("Quantidade de calor");
            op3.setText("Forma de enegia termica liberada");
            op4.setText("Aumento da temperatura");
        }
        if (x == 7) {
            if (op1.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: A");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: A");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("8-Qual desses NÃO é um fenônemo quimico?");
            perg2.setText(" ");
            op1.setText("queima de fogos de artifício");
            op2.setText("água sanitária em tecido colorido");
            op3.setText("Dilatação dos corpos");
            op4.setText("O enferrujamento do ferro");
        }
        if (x == 8) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("9-O carbono possui quantos eletrons na camdada?");
            perg2.setText("de valência?");
            op1.setText("2 elétrons");
            op2.setText("nenhum elétron");
            op3.setText("3 elétrons");
            op4.setText("4 elétrons");
        }
        if (x == 9) {
            if (op4.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: D");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: D");
            }
            op1.setSelected(false);
            op2.setSelected(false);
            op3.setSelected(false);
            op4.setSelected(false);
            perg1.setText("10-Quimica Inorgânica é também conhecidada");
            perg2.setText("como? ");
            op1.setText("química moderna");
            op2.setText("química Sem elementos");
            op3.setText("Química mineral");
            op4.setText("Quimica sem-carbono");
            
        }
        if (x == 10) {
            if (op3.isSelected()) {
                cont++;
                JOptionPane.showMessageDialog(null, "Resposta Correta \nOpção Correta: C");
            } else {
                JOptionPane.showMessageDialog(null, "Resposta Errada \nOpção Correta: C");
            }
            JOptionPane.showMessageDialog(null,"Você Acertou:"+cont+"/10 questões");
            new PerguntasMaster().show();
            this.dispose();
        }
        x++;
}//GEN-LAST:event_jButton1ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        op1.setSelected(true);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        op1.setSelected(false);
        op2.setSelected(true);
        op3.setSelected(false);
        op4.setSelected(false);
}//GEN-LAST:event_op2ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(true);
        op4.setSelected(false);
}//GEN-LAST:event_op3ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        
        op1.setSelected(false);
        op2.setSelected(false);
        op3.setSelected(false);
        op4.setSelected(true);
}//GEN-LAST:event_op4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PergQuim().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JLabel perg1;
    private javax.swing.JLabel perg2;
    // End of variables declaration//GEN-END:variables
}
