package schoolmaster10;

import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Raciocinio.java
 *
 * Created on 11/10/2011, 12:06:01
 */
/**
 *
 * @author Douglas
 */
public class Raciocinio extends javax.swing.JFrame {

    /** Creates new form Raciocinio */
    public Raciocinio() {
        initComponents();
        this.setLocationRelativeTo(null);
         this.setResizable(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ckb1 = new javax.swing.JCheckBox();
        ckb2 = new javax.swing.JCheckBox();
        ckb3 = new javax.swing.JCheckBox();
        ckb4 = new javax.swing.JCheckBox();
        ckb5 = new javax.swing.JCheckBox();
        ckb6 = new javax.swing.JCheckBox();
        ckb7 = new javax.swing.JCheckBox();
        ckb8 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JComboBox();
        cb8 = new javax.swing.JComboBox();
        cb12 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        cb7 = new javax.swing.JComboBox();
        cb11 = new javax.swing.JComboBox();
        cb10 = new javax.swing.JComboBox();
        cb6 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb5 = new javax.swing.JComboBox();
        cb9 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setEnabled(false);
        jPanel2.setName("jPanel2"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setName("jPanel1"); // NOI18N

        ckb1.setBackground(new java.awt.Color(204, 204, 204));
        ckb1.setForeground(new java.awt.Color(255, 255, 255));
        ckb1.setText("O Primeiro do Lado direito usa Tênis Ecko");
        ckb1.setEnabled(false);
        ckb1.setName("ckb1"); // NOI18N

        ckb2.setBackground(new java.awt.Color(204, 204, 204));
        ckb2.setForeground(new java.awt.Color(255, 255, 255));
        ckb2.setText("O que usa camisa verde usa nike");
        ckb2.setEnabled(false);
        ckb2.setName("ckb2"); // NOI18N

        ckb3.setBackground(new java.awt.Color(204, 204, 204));
        ckb3.setForeground(new java.awt.Color(255, 255, 255));
        ckb3.setText("Quem tem computador Dell está do lado esquerdo de quem usa Qix");
        ckb3.setEnabled(false);
        ckb3.setName("ckb3"); // NOI18N

        ckb4.setBackground(new java.awt.Color(204, 204, 204));
        ckb4.setForeground(new java.awt.Color(255, 255, 255));
        ckb4.setText("O que tem um iMac fica vizinho do que tem camisa preta");
        ckb4.setEnabled(false);
        ckb4.setName("ckb4"); // NOI18N

        ckb5.setBackground(new java.awt.Color(204, 204, 204));
        ckb5.setForeground(new java.awt.Color(255, 255, 255));
        ckb5.setText("Eudes usa computador iMac");
        ckb5.setEnabled(false);
        ckb5.setName("ckb5"); // NOI18N

        ckb6.setBackground(new java.awt.Color(204, 204, 204));
        ckb6.setForeground(new java.awt.Color(255, 255, 255));
        ckb6.setText("Quem está com a camisa Branca está  lado direiro de quem usa nike");
        ckb6.setEnabled(false);
        ckb6.setName("ckb6"); // NOI18N

        ckb7.setBackground(new java.awt.Color(204, 204, 204));
        ckb7.setForeground(new java.awt.Color(255, 255, 255));
        ckb7.setText("Douglas usa Adidas");
        ckb7.setEnabled(false);
        ckb7.setName("ckb7"); // NOI18N

        ckb8.setBackground(new java.awt.Color(204, 204, 204));
        ckb8.setForeground(new java.awt.Color(255, 255, 255));
        ckb8.setText("Que usa IBM está do Lado de que tem camisa Azul");
        ckb8.setEnabled(false);
        ckb8.setName("ckb8"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckb2)
                    .addComponent(ckb1)
                    .addComponent(ckb4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ckb3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckb5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ckb6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ckb7, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckb8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckb7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb8)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Verde", "Azul", "Preta", "Branca" }));
        cb4.setName("cb4"); // NOI18N
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        cb8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Nike", "Qix", "Ecko", "Adidas" }));
        cb8.setName("cb8"); // NOI18N
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });

        cb12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Vaio", "iMac", "Dell", "IBM" }));
        cb12.setName("cb12"); // NOI18N
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lairton");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lucemir");
        jLabel3.setName("jLabel3"); // NOI18N

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Verde", "Azul", "Preta", "Branca" }));
        cb3.setName("cb3"); // NOI18N
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        cb7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Nike", "Qix", "Ecko", "Adidas" }));
        cb7.setName("cb7"); // NOI18N
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });

        cb11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Vaio", "iMac", "Dell", "IBM" }));
        cb11.setName("cb11"); // NOI18N
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });

        cb10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Vaio", "iMac", "Dell", "IBM" }));
        cb10.setName("cb10"); // NOI18N
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });

        cb6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Nike", "Qix", "Ecko", "Adidas" }));
        cb6.setName("cb6"); // NOI18N
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Verde", "Azul", "Preta", "Branca" }));
        cb2.setName("cb2"); // NOI18N
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eudes");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Douglas");
        jLabel1.setName("jLabel1"); // NOI18N

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Verde", "Azul", "Preta", "Branca" }));
        cb1.setName("cb1"); // NOI18N
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Nike", "Qix", "Ecko", "Adidas" }));
        cb5.setName("cb5"); // NOI18N
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Vaio", "iMac", "Dell", "IBM" }));
        cb9.setName("cb9"); // NOI18N
        cb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb9ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Computador");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tênis");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Camisa");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Teste de QI");
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cb10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        String camisa1,camisa2,camisa3,camisa4,tenis1,tenis2,tenis3,tenis4,pc1,pc2,pc3,pc4;
    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb2
        if ((("Verde".equals(camisa1)) && ("Nike".equals(tenis1))) || (("Verde".equals(camisa2)) && ("Nike".equals(tenis2))) || (("Verde".equals(camisa3)) && ("Nike".equals(tenis3))) || (("Verde".equals(camisa4)) && ("Nike".equals(tenis4)))) {
            ckb2.setSelected(true);
        } else {
            ckb2.setSelected(false);
        }
        // fim ckb2
        // ckb4
        if ((("iMac".equals(pc1)) && ("Preta".equals(camisa2))) || (("iMac".equals(pc2)) && ("Preta".equals(camisa1))) || (("iMac".equals(pc2)) && ("Preta".equals(camisa3))) || (("iMac".equals(pc3)) && ("Preta".equals(camisa2))) || (("iMac".equals(pc3)) && ("Preta".equals(camisa4))) || (("iMac".equals(pc4)) && ("Preta".equals(camisa3)))) {
            ckb4.setSelected(true);
        } else {
            ckb4.setSelected(false);
        }
        //fim ckb4
         // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
            camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb2
        if ((("Verde".equals(camisa1)) && ("Nike".equals(tenis1))) || (("Verde".equals(camisa2)) && ("Nike".equals(tenis2))) || (("Verde".equals(camisa3)) && ("Nike".equals(tenis3))) || (("Verde".equals(camisa4)) && ("Nike".equals(tenis4)))) {
            ckb2.setSelected(true);
        } else {
            ckb2.setSelected(false);
        }
        // fim ckb2
        // ckb4
        if ((("iMac".equals(pc1)) && ("Preta".equals(camisa2))) || (("iMac".equals(pc2)) && ("Preta".equals(camisa1))) || (("iMac".equals(pc2)) && ("Preta".equals(camisa3))) || (("iMac".equals(pc3)) && ("Preta".equals(camisa2))) || (("iMac".equals(pc3)) && ("Preta".equals(camisa4))) || (("iMac".equals(pc4)) && ("Preta".equals(camisa3)))) {
            ckb4.setSelected(true);
        } else {
            ckb4.setSelected(false);
        }
        //fim ckb4
        // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            // ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
            // ckb4
        if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
        // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
            camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            // ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
           // ckb4
        if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
        // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            // ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
            // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
        // cbk7
        if ("Adidas".equals(tenis1)){
            ckb7.setSelected(true);
        }
        else{
            ckb7.setSelected(false);
        }
        // fim ckb7
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            // ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
            // ckb3
            if((("Dell".equals(pc1))&&("Qix".equals(tenis2)))||(("Dell".equals(pc3))&&("Qix".equals(tenis4)))||(("Dell".equals(pc2))&&("Qix".equals(tenis3))) ){
                ckb3.setSelected(true);
            }
            else{
                ckb3.setSelected(false);
            }
            // fim ckb3
            // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
            
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            //  ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
            //ckb5
        if ("iMac".equals(pc2)) {
            ckb5.setSelected(true);
        } else {
            ckb5.setSelected(false);
        }
        //fim ckb5
        // ckb6
        if ((("Branca".equals(camisa2)) && ("Nike".equals(tenis1)))||(("Branca".equals(camisa3)) && ("Nike".equals(tenis2)))||(("Branca".equals(camisa4)) && ("Nike".equals(tenis3)))){
            ckb6.setSelected(true);
        }
        else{
            ckb6.setSelected(false);
        }
        // fim do cbk6
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
           camisa1 = (String) cb1.getSelectedItem();
            tenis1 = (String) cb5.getSelectedItem();
            pc1 = (String) cb9.getSelectedItem();
            camisa2 = (String) cb2.getSelectedItem();
            tenis2 = (String) cb6.getSelectedItem();
            pc2 = (String) cb10.getSelectedItem();
            camisa3 = (String) cb3.getSelectedItem();
            tenis3 = (String) cb7.getSelectedItem();
            pc3 = (String) cb11.getSelectedItem();
            camisa4 = (String) cb4.getSelectedItem();
            tenis4 = (String) cb8.getSelectedItem();
            pc4 = (String) cb12.getSelectedItem();
            // 1 ckb1
            if ("Ecko".equals(tenis4)){
            ckb1.setSelected(true);
            }
            else{
              ckb1.setSelected(false); 
            }
            // fim ckb1    
            // ckb2
            if( (("Verde".equals(camisa1)) && ("Nike".equals(tenis1)))||(("Verde".equals(camisa2)) && ("Nike".equals(tenis2)))||(("Verde".equals(camisa3)) && ("Nike".equals(tenis3)))||(("Verde".equals(camisa4)) && ("Nike".equals(tenis4))) ){
                ckb2.setSelected(true);
            }
            else{
                ckb2.setSelected(false);
            }
            // fim ckb2
            // ckb3
            if((("Dell".equals(pc1))&&("Qix".equals(tenis2)))||(("Dell".equals(pc3))&&("Qix".equals(tenis4)))||(("Dell".equals(pc2))&&("Qix".equals(tenis3))) ){
                ckb3.setSelected(true);
            }
            else{
                ckb3.setSelected(false);
            }
            // fim ckb3
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb9ActionPerformed
         camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb3
            if((("Dell".equals(pc1))&&("Qix".equals(tenis2)))||(("Dell".equals(pc3))&&("Qix".equals(tenis4)))||(("Dell".equals(pc2))&&("Qix".equals(tenis3))) ){
                ckb3.setSelected(true);
            }
            else{
                ckb3.setSelected(false);
            }
            // fim ckb3
            // ckb4
            if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
            // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb9ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb3
            if((("Dell".equals(pc1))&&("Qix".equals(tenis2)))||(("Dell".equals(pc3))&&("Qix".equals(tenis4)))||(("Dell".equals(pc2))&&("Qix".equals(tenis3))) ){
                ckb3.setSelected(true);
            }
            else{
                ckb3.setSelected(false);
            }
            // fim ckb3
        
        // ckb4
        if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
        //ckb5
        if ("iMac".equals(pc2)) {
            ckb5.setSelected(true);
        } else {
            ckb5.setSelected(false);
        }
        //fim ckb5
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb10ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb3
            if((("Dell".equals(pc1))&&("Qix".equals(tenis2)))||(("Dell".equals(pc3))&&("Qix".equals(tenis4)))||(("Dell".equals(pc2))&&("Qix".equals(tenis3))) ){
                ckb3.setSelected(true);
            }
            else{
                ckb3.setSelected(false);
            }
            // fim ckb3
            // ckb4
        if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
    }//GEN-LAST:event_cb11ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        camisa1 = (String) cb1.getSelectedItem();
        tenis1 = (String) cb5.getSelectedItem();
        pc1 = (String) cb9.getSelectedItem();
        camisa2 = (String) cb2.getSelectedItem();
        tenis2 = (String) cb6.getSelectedItem();
        pc2 = (String) cb10.getSelectedItem();
        camisa3 = (String) cb3.getSelectedItem();
        tenis3 = (String) cb7.getSelectedItem();
        pc3 = (String) cb11.getSelectedItem();
        camisa4 = (String) cb4.getSelectedItem();
        tenis4 = (String) cb8.getSelectedItem();
        pc4 = (String) cb12.getSelectedItem();
        // ckb4
        if( (("iMac".equals(pc1)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa1)))||(("iMac".equals(pc2)) && ("Preta".equals(camisa3)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa2)))||(("iMac".equals(pc3)) && ("Preta".equals(camisa4)))||(("iMac".equals(pc4)) && ("Preta".equals(camisa3))) ){
                ckb4.setSelected(true);
            }
            else{
                ckb4.setSelected(false);
            }
            //fim ckb4
        // ckb8
        if( (("IBM".equals(pc1)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa1)))||(("IBM".equals(pc2)) && ("Azul".equals(camisa3)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa2)))||(("IBM".equals(pc3)) && ("Azul".equals(camisa4)))||(("IBM".equals(pc4)) && ("Azul".equals(camisa3))) ){
                ckb8.setSelected(true);
            }
            else{
                ckb8.setSelected(false);
            }
            //fim ckb8
        if( ("Preta".equals(camisa1)) &&("Azul".equals(camisa2))&&("Verde".equals(camisa3))&&("Branca".equals(camisa4))&&("Adidas".equals(tenis1))&&("Qix".equals(tenis2))&&("Nike".equals(tenis3))&&("Ecko".equals(tenis4))&&("Dell".equals(pc1))&&("iMac".equals(pc2))&&("IBM".equals(pc3))&&("Vaio".equals(pc4))){
            JOptionPane.showMessageDialog(null,"Parabens");
            this.dispose();
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Raciocinio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb10;
    private javax.swing.JComboBox cb11;
    private javax.swing.JComboBox cb12;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JComboBox cb4;
    private javax.swing.JComboBox cb5;
    private javax.swing.JComboBox cb6;
    private javax.swing.JComboBox cb7;
    private javax.swing.JComboBox cb8;
    private javax.swing.JComboBox cb9;
    private javax.swing.JCheckBox ckb1;
    private javax.swing.JCheckBox ckb2;
    private javax.swing.JCheckBox ckb3;
    private javax.swing.JCheckBox ckb4;
    private javax.swing.JCheckBox ckb5;
    private javax.swing.JCheckBox ckb6;
    private javax.swing.JCheckBox ckb7;
    private javax.swing.JCheckBox ckb8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
